### ISSUE TITLE
以源码运行错误

### ISSUE THREAD

**Issue by Liner03** [shanmiteko/LotteryAutoScript#183]
### 描述Bug

正常下载以及配置后运行出错

### 重现Bug

正常运行后出错

### 预期行为

正常运行

### 截图

![image](https://user-images.githubusercontent.com/38096847/185901102-3f5badc8-f78a-4a35-87b6-08b1643944ec.png)

### 运行日志

(node:154293) UnhandledPromiseRejectionWarning: TypeError: LotteryOrder.map(...).filter(...).flatMap is not a function
    at Object.init (/root/bilibili/LotteryAutoScript/lib/data/global_var.js:45:22)
    at main (/root/bilibili/LotteryAutoScript/main.js:49:26)
    at main (/root/bilibili/LotteryAutoScript/main.js:37:35)
    at /root/bilibili/LotteryAutoScript/main.js:153:27
    at Object.<anonymous> (/root/bilibili/LotteryAutoScript/main.js:169:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:154293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:154293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 操作系统

arm64 ubuntu20.04

### NodeJs版本

10.19.0

### 脚本版本

2.6.0

**Comment by shanmiteko** [comment]
至少node14以上
