### ISSUE TITLE
使用类似宝塔的定时任务出错

### ISSUE THREAD

**Issue by y7rr** [shanmiteko/LotteryAutoScript#218]
### 描述Bug

使用类似宝塔的定时任务出错
这个面板https://github.com/midoks/mdserver-web

### 重现Bug

定时任务出错

### 预期行为

正确运行

### 运行日志

``````````
[2022-11-02T10:58:51.032+08] [Info] [帐号1 环境变量初始化] [成功加载env.js文件]
[2022-11-02T10:58:51.034+08] [Info] [帐号1 配置文件初始化] [成功加载my_config.js文件]
(node:1978303) UnhandledPromiseRejectionWarning: TypeError: LotteryOrder.map(...).filter(...).flatMap is not a function
    at Object.init (/root/LotteryAutoScript/lib/data/global_var.js:45:22)
    at main (/root/LotteryAutoScript/main.js:49:26)
    at main (/root/LotteryAutoScript/main.js:37:35)
    at /root/LotteryAutoScript/main.js:158:27
    at Object.<anonymous> (/root/LotteryAutoScript/main.js:174:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:1978303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1978303) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----------------------------------------------------------------------------
★[2022-11-02 02:58:51] Successful
----------------------------------------------------------------------------

> lottery-auto-script@2.6.6 start /root/LotteryAutoScript
> node main.js start

  _           _   _                   _____           _       _   
 | |         | | | |                 / ____|         (_)     | |  
 | |     ___ | |_| |_ ___ _ __ _   _| (___   ___ _ __ _ _ __ | |_ 
 | |    / _ \| __| __/ _ \ '__| | | |\___ \ / __| '__| | '_ \| __|
 | |___| (_) | |_| ||  __/ |  | |_| |____) | (__| |  | | |_) | |_ 
 |______\___/ \__|\__\___|_|   \__, |_____/ \___|_|  |_| .__/ \__|
                                __/ |                  | |        
                               |___/                   |_|        
                                                                  
    This: v2.6.6     Nodejs: v10.19.0     Written By shanmite
[2022-11-02T10:59:26.666+08] [Info] [帐号1 环境变量初始化] [成功加载env.js文件]
[2022-11-02T10:59:26.668+08] [Info] [帐号1 配置文件初始化] [成功加载my_config.js文件]
(node:1978346) UnhandledPromiseRejectionWarning: TypeError: LotteryOrder.map(...).filter(...).flatMap is not a function
    at Object.init (/root/LotteryAutoScript/lib/data/global_var.js:45:22)
    at main (/root/LotteryAutoScript/main.js:49:26)
    at main (/root/LotteryAutoScript/main.js:37:35)
    at /root/LotteryAutoScript/main.js:158:27
    at Object.<anonymous> (/root/LotteryAutoScript/main.js:174:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:1978346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1978346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``````````````````````

### 操作系统

ubutun 22

### 脚本版本

最新

**Comment by shanmiteko** [comment]
提供一下nodejs版本

**Comment by shanmiteko** [comment]
升级一下nodejs

**Comment by 8ty** [comment]
我好像也出现一样的，而且我的已经是18的最新稳定版了

**Comment by 8ty** [comment]
> 我好像也出现一样的，而且我的已经是18的最新稳定版了

手动运行就行，但是定时不行

**Comment by 8ty** [comment]
> > 我好像也出现一样的，而且我的已经是18的最新稳定版了
> 
> 手动运行就行，但是定时不行

我是设定了定时运行这个命令

cd /root/LotteryAutoScript && npm i && npm run start



![image](https://user-images.githubusercontent.com/92656899/200229746-89679624-13a3-46df-b2d1-96e3678465cb.png)
