### ISSUE TITLE
话题搜索 执行报错,异常终止

### ISSUE THREAD

**Issue by chuzai1** [shanmiteko/LotteryAutoScript#285]
### 描述Bug

[2023-05-16T05:24:56.657+08] [Warn] [帐号1 处理动态数据] [
未找到任何动态信息
]
/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:197
                : /(?<=next_offset":)[0-9]+/.exec(res)[0]
                                                      ^

TypeError: Cannot read properties of null (reading '0')
    at modifyDynamicRes (/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:197:55)
    at Monitor.getLotteryInfoByTag (/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:359:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.filterLotteryInfo (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:272:32)
    at async Monitor.startLottery (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:107:28)
    at async Monitor.init (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:50:24)
    at async EventEmitter.<anonymous> (/ql/data/scripts/LotteryAutoScript3/lib/lottery.js:53:13)

### 重现Bug

正常执行,报错终止

### 预期行为

正常执行

### 运行日志

[2023-05-16T05:24:56.657+08] [Warn] [帐号7 处理动态数据] [
未找到任何动态信息
]
/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:197
                : /(?<=next_offset":)[0-9]+/.exec(res)[0]
                                                      ^

TypeError: Cannot read properties of null (reading '0')
    at modifyDynamicRes (/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:197:55)
    at Monitor.getLotteryInfoByTag (/ql/data/scripts/LotteryAutoScript3/lib/core/searcher.js:359:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.filterLotteryInfo (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:272:32)
    at async Monitor.startLottery (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:107:28)
    at async Monitor.init (/ql/data/scripts/LotteryAutoScript3/lib/core/monitor.js:50:24)
    at async EventEmitter.<anonymous> (/ql/data/scripts/LotteryAutoScript3/lib/lottery.js:53:13)

### 操作系统

win11

### NodeJs版本

lottery-auto-script-node18-win-x64.zip

### 脚本版本

2.7.9

**Comment by shanmiteko** [comment]
话题被删除 https://www.bilibili.com/v/topic/detail/?topic_id=3230836
