### ISSUE TITLE
经常报错中断

### ISSUE THREAD

**Issue by Taoja** [shanmiteko/LotteryAutoScript#291]
### 描述Bug

F:\自动抽奖\lib\core\searcher.js:193
                : /(?<=next_offset":)[0-9]+/.exec(res)[0]
                                                      ^

TypeError: Cannot read properties of null (reading '0')
    at modifyDynamicRes (F:\自动抽奖\lib\core\searcher.js:193:55)
    at Monitor.getLotteryInfoByTag (F:\自动抽奖\lib\core\searcher.js:355:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.filterLotteryInfo (F:\自动抽奖\lib\core\monitor.js:256:32)
    at async Monitor.startLottery (F:\自动抽奖\lib\core\monitor.js:109:28)
    at async Monitor.init (F:\自动抽奖\lib\core\monitor.js:50:24)
    at async EventEmitter.<anonymous> (F:\自动抽奖\lib\lottery.js:53:13)

Node.js v18.14.2

### 重现Bug

开一段时间后就报错了。

### 预期行为

不报错正常运行

### 运行日志

F:\自动抽奖\lib\core\searcher.js:193
                : /(?<=next_offset":)[0-9]+/.exec(res)[0]
                                                      ^

TypeError: Cannot read properties of null (reading '0')
    at modifyDynamicRes (F:\自动抽奖\lib\core\searcher.js:193:55)
    at Monitor.getLotteryInfoByTag (F:\自动抽奖\lib\core\searcher.js:355:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.filterLotteryInfo (F:\自动抽奖\lib\core\monitor.js:256:32)
    at async Monitor.startLottery (F:\自动抽奖\lib\core\monitor.js:109:28)
    at async Monitor.init (F:\自动抽奖\lib\core\monitor.js:50:24)
    at async EventEmitter.<anonymous> (F:\自动抽奖\lib\lottery.js:53:13)

Node.js v18.14.2

### 操作系统

windows10跑gitee上的源码

### NodeJs版本

18.14.2

### 脚本版本

Gitee上源码

**Comment by shanmiteko** [comment]
用github或gitlab上的版本，gitee不是最新的
