### ISSUE TITLE
获取动态出错

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#354]
### 描述Bug

无法正常获取动态信息

### 重现Bug

每次运行跑到提取专栏(32781196)中的动态就报错

### 预期行为

正常获取

### 运行日志

[2024-03-08T06:34:29.317+08] [Info] [帐号1 获取动态] [动态(897094994595151876)已转发过]
[2024-03-08T06:34:29.317+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(900906803841204233) (2)]
[2024-03-08T06:34:29.415+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:29.415+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:34:34.421+08] [Info] [帐号1 获取动态] [动态(900906803841204233)已转发过]
[2024-03-08T06:34:34.421+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(906159870959419431) (1)]
[2024-03-08T06:34:34.514+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:34.514+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:34:39.812+08] [Info] [帐号1 获取动态] [提取专栏(32781196)中提及的dyid(202)]
[2024-03-08T06:34:39.812+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905441430308126743) (202)]
[2024-03-08T06:34:39.923+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:39.923+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:34:44.930+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(903711589281038340) (201)]
[2024-03-08T06:34:45.030+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:45.030+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:34:50.031+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905637955127738375) (200)]
[2024-03-08T06:34:50.117+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:50.117+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:34:55.122+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905407628901875716) (199)]
[2024-03-08T06:34:55.235+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:34:55.235+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:00.239+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(904712406855319552) (198)]
[2024-03-08T06:35:00.337+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:00.337+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:05.343+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(904883097430917125) (197)]
[2024-03-08T06:35:05.439+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:05.439+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:10.441+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(900826466449621011) (196)]
[2024-03-08T06:35:10.548+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:10.549+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:15.556+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(906022487817453584) (195)]
[2024-03-08T06:35:15.660+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:15.660+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:20.666+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905637156239704088) (194)]
[2024-03-08T06:35:20.755+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:20.755+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:25.758+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(904291422741463072) (193)]
[2024-03-08T06:35:25.860+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:25.860+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:30.862+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905774036832747520) (192)]
[2024-03-08T06:35:30.953+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:30.953+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:35.956+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(903904033843970072) (191)]
[2024-03-08T06:35:36.095+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:36.095+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:41.101+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(905771038984372240) (190)]
[2024-03-08T06:35:41.195+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:41.195+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:46.202+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(904261843283869701) (189)]
[2024-03-08T06:35:46.307+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:46.307+08] [Info] [帐号1 时延] [5000ms]
[2024-03-08T06:35:51.308+08] [Info] [帐号1 获取动态] [查看专栏中所提及动态(904617573973229568) (188)]
[2024-03-08T06:35:51.414+08] [Info] [帐号1 获取一个动态的细节] [ok]
[2024-03-08T06:35:51.414+08] [Info] [帐号1 时延] [5000ms]
/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:66
        , { is_liked = 1, user_profile = {} } = desc
            ^

TypeError: Cannot read properties of null (reading 'is_liked')
    at parseDynamicCard (/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:66:13)
    at Monitor.getLotteryInfoByArticle (/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:481:45)
    at async Monitor.filterLotteryInfo (/ql/data/scripts/LotteryAutoScript/lib/core/monitor.js:275:32)
    at async Monitor.startLottery (/ql/data/scripts/LotteryAutoScript/lib/core/monitor.js:108:28)
    at async Monitor.init (/ql/data/scripts/LotteryAutoScript/lib/core/monitor.js:51:24)
    at async EventEmitter.<anonymous> (/ql/data/scripts/LotteryAutoScript/lib/lottery.js:53:13)

Node.js v18.19.1

### 操作系统

qinglong 2.17.2

### NodeJs版本

v18.19.1

### 脚本版本

v2.8.14.2

**Comment by zheteng2021219** [comment]
是的，下载最新版[v2.8.14.2]，打开显示版本确是[v2.8.13]，同样就是显示这个问题 ：获取动态数据出错。

**Comment by tslace** [comment]
运行init.sh，一直是2.8.13,更新不到最新版。。。

**Comment by lll666666** [comment]
> 运行init.sh，一直是2.8.13,更新不到最新版。。。

有没有可能要运行update

**Comment by lll666666** [comment]
> > > 运行init.sh，一直是2.8.13,更新不到最新版。。。
> > 
> > 
> > 有没有可能要运行update
> 
> 就算是直接在这里下载最新的zip再解压覆盖，也一样不行啊

看了下好像是作者没有更新版本号

**Comment by lll666666** [comment]
急急急，老是报这错

**Comment by lll666666** [comment]
@shanmiteko  用这个https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=  好像可以识别官方和非官方抽奖和预约抽奖奖品        有空的话看看
预约抽奖 https://www.bilibili.com/opus/906869287881277496
官方抽奖 https://www.bilibili.com/opus/906478621961486353
非官方抽奖 https://www.bilibili.com/opus/905246103786487859

**Comment by MinanaYaa** [comment]
> > 运行init.sh，一直是2.8.13,更新不到最新版。。。
> 
> 有没有可能要运行update

为什么我运行不了update.sh，明明把lottery拉进去了，是不支持ql吗

**Comment by lll666666** [comment]
> > > 运行init.sh，一直是2.8.13,更新不到最新版。。。
> > 
> > 
> > 有没有可能要运行update
> 
> 为什么我运行不了update.sh，明明把lottery拉进去了，是不支持ql吗

看仔细教程，是能在青龙跑的 https://github.com/shanmiteko/LotteryAutoScript/blob/main/doc/run_use_ql.md

**Comment by tslace** [comment]
清空不用运行update,直接运行开始的init文件就可以升级

**Comment by lll666666** [comment]
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/98231341/6164c480-5b51-4852-ae18-7f8ab56fe016)
v666 确实可以识别是不是官抽，但我改源码报错，v1改v666

node:internal/url:775
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at send (/ql/data/scripts/LotteryAutoScript/lib/net/http.js:71:21)
    at /ql/data/scripts/LotteryAutoScript/lib/net/bili.js:91:9
    at new Promise (<anonymous>)
    at get (/ql/data/scripts/LotteryAutoScript/lib/net/bili.js:90:12)
    at bili_client._getOneDynamicByDyid.get.url (/ql/data/scripts/LotteryAutoScript/lib/net/bili.js:451:25)
    at Line.run (/ql/data/scripts/LotteryAutoScript/lib/net/bili.js:60:46)
    at Object.getOneDynamicByDyid (/ql/data/scripts/LotteryAutoScript/lib/net/bili.js:496:42)
    at Monitor.getLotteryInfoByArticle (/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:474:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_URL',
  input: 'undefined'
}

Node.js v20.11.1

用的reqable，请求头加cookie就可以，不然请求不到数据，用浏览器访问要登陆B站账号，不然没数据
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/98231341/42bb7abc-6af4-4cc1-88e5-19501f35b5e8)

**Comment by MinanaYaa** [comment]
> 青龙不用运行update,直接运行开始的init文件就可以升级

可是我不管怎么运行init都更新不了，一直停在v2.8.13

**Comment by MinanaYaa** [comment]
> > > > 运行init.sh，一直是2.8.13,更新不到最新版。。。
> > > 
> > > 
> > > 有没有可能要运行update
> > 
> > 
> > 为什么我运行不了update.sh，明明把lottery拉进去了，是不支持ql吗
> 
> 看仔细教程，是能在青龙跑的 https://github.com/shanmiteko/LotteryAutoScript/blob/main/doc/run_use_ql.md

我就是安装这个教程跑了一年多了现在版本卡在v2.8.13，运行不了，我看最新版已经修复那个错误了想更新

**Comment by tslace** [comment]
把lib／net下的两个带有bili的文件删掉，再运行init。

**Comment by MinanaYaa** [comment]
> 把lib／net下的两个带有bili的文件删掉，再运行init。
error: inflate: data stream error (invalid code lengths set)
error: unable to unpack addb9c65feb35c5ccb072bb660ae1755a2f17023 header
fatal: loose object addb9c65feb35c5ccb072bb660ae1755a2f17023 (stored in .git/objects/ad/db9c65feb35c5ccb072bb660ae1755a2f17023) is corrupt

报错了

**Comment by lll666666** [comment]
> > 把lib／net下的两个带有bili的文件删掉，再运行init。
> > error: inflate: data stream error (invalid code lengths set)
> > error: unable to unpack [addb9c6](https://github.com/shanmiteko/LotteryAutoScript/commit/addb9c65feb35c5ccb072bb660ae1755a2f17023) header
> > fatal: loose object [addb9c6](https://github.com/shanmiteko/LotteryAutoScript/commit/addb9c65feb35c5ccb072bb660ae1755a2f17023) (stored in .git/objects/ad/db9c65feb35c5ccb072bb660ae1755a2f17023) is corrupt
> 
> 报错了

实在不行把配置文件config env 保存起来，把脚本删了重新拉

**Comment by tslace** [comment]
也可以单独从作者库下载下来这两个文件（或者复制里面的内容），然后放进目录里。

**Comment by shanmiteko** [comment]
duplicate #349
