### ISSUE TITLE
 This: v2.8.16     Nodejs: v18.5.0  

### ISSUE THREAD

**Issue by zheteng2021219** [shanmiteko/LotteryAutoScript#369]
### 描述Bug

 This: v2.8.16     Nodejs: v18.5.0
最新版抽奖会出现图1的BUG。
清理动态和关注有BUG，无法清理动态和关注。如图2和图3。

### 重现Bug

 This: v2.8.16     Nodejs: v18.5.0
最新版抽奖会出现图1的BUG。
清理动态和关注有BUG，无法清理动态和关注。如图2和图3。

### 预期行为

 This: v2.8.16     Nodejs: v18.5.0
最新版抽奖会出现图1的BUG。
清理动态和关注有BUG，无法清理动态和关注。如图2和图3。

### 截图

![1](https://github.com/shanmiteko/LotteryAutoScript/assets/79276564/f7e0b58a-fe4c-4f0c-9dbf-9ec222b81278)
![2](https://github.com/shanmiteko/LotteryAutoScript/assets/79276564/c75d1e9b-2c2a-4340-995d-9ba723beada2)
![3](https://github.com/shanmiteko/LotteryAutoScript/assets/79276564/5b67f21e-7498-4d20-ae91-f3892b9581da)

### 运行日志

 This: v2.8.16     Nodejs: v18.5.0

### 操作系统

WIN10

### NodeJs版本

Nodejs: v18.5.0

### 脚本版本

 This: v2.8.16

### 其他

 This: v2.8.16     Nodejs: v18.5.0

**Comment by Dlian-Zero** [comment]
/ql/scripts/LotteryAutoScript/lib/core/searcher.js:74
    obj.uid = desc.uid
                   ^

TypeError: Cannot read properties of null (reading 'uid')
    at parseDynamicCard (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:74:20)
    at Monitor.getLotteryInfoByArticle (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:479:45)
    at async Monitor.filterLotteryInfo (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:269:32)
    at async Monitor.startLottery (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:108:28)
    at async Monitor.init (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:51:24)
    at async EventEmitter.<anonymous> (/ql/scripts/LotteryAutoScript/lib/lottery.js:53:13)

**Comment by Dlian-Zero** [comment]
**运行日志**
SyntaxError: Unexpected end of JSON input

]
/ql/scripts/LotteryAutoScript/lib/core/searcher.js:74
    obj.uid = desc.uid
                   ^

TypeError: Cannot read properties of null (reading 'uid')
    at parseDynamicCard (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:74:20)
    at Monitor.getLotteryInfoByArticle (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:479:45)
    at async Monitor.filterLotteryInfo (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:269:32)
    at async Monitor.startLottery (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:108:28)
    at async Monitor.init (/ql/scripts/LotteryAutoScript/lib/core/monitor.js:51:24)
    at async EventEmitter.<anonymous> (/ql/scripts/LotteryAutoScript/lib/lottery.js:53:13)

**操作系统**
qinglong

**NodeJs版本**
 v16.13.1
**脚本版本**
This: v2.8.16

**其他**
This: v2.8.16 Nodejs: v18.5.0

**Comment by ww176883** [comment]
这个问题我也遇到了,desc是个null,跳过就好了
