### ISSUE TITLE
账号转发动态途中被系统强制登出，任务直接终止

### ISSUE THREAD

**Issue by xiaobuboy** [shanmiteko/LotteryAutoScript#392]
### 描述Bug

账号转发动态途中被系统强制登出，任务直接就终止，后面的账号没有继续进行转发。能否使当前账号被系统登出情况下跳过该账号，让后续账号继续转发动态？下面是相关报错：
[2024-05-13T16:16:45.902+08] [Warn] [帐号7 处理动态数据] [
未找到任何动态信息
]
/ql/scripts/LotteryAutoScript/lib/core/searcher.js:360
    log.info('处理动态数据', `动态数据读取完毕(${cards.length})(${next.has_more})`);
                                         ^

TypeError: Cannot read properties of null (reading 'length')
    at modifyDynamicRes (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:360:42)
    at Function.checkAllDynamic (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:405:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.retryfn (/ql/scripts/LotteryAutoScript/lib/utils.js:77:19)
    at async createRandomDynamic (/ql/scripts/LotteryAutoScript/lib/lottery.js:15:45)
    at async EventEmitter.<anonymous> (/ql/scripts/LotteryAutoScript/lib/lottery.js:63:13)

Node.js v17.5.0

### 重现Bug

1

### 预期行为

1

### 运行日志

[2024-05-13T16:16:45.902+08] [Warn] [帐号7 处理动态数据] [
未找到任何动态信息
]
/ql/scripts/LotteryAutoScript/lib/core/searcher.js:360
    log.info('处理动态数据', `动态数据读取完毕(${cards.length})(${next.has_more})`);
                                         ^

TypeError: Cannot read properties of null (reading 'length')
    at modifyDynamicRes (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:360:42)
    at Function.checkAllDynamic (/ql/scripts/LotteryAutoScript/lib/core/searcher.js:405:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.retryfn (/ql/scripts/LotteryAutoScript/lib/utils.js:77:19)
    at async createRandomDynamic (/ql/scripts/LotteryAutoScript/lib/lottery.js:15:45)
    at async EventEmitter.<anonymous> (/ql/scripts/LotteryAutoScript/lib/lottery.js:63:13)

Node.js v17.5.0

### 操作系统

青龙面板

### 脚本版本

v2.9.0

**Comment by 6uu1** [comment]
我也是，不过好像是内存不够然后终止了？
我的报错：
````
node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: Cannot read properties of null (reading 'length')
    at modifyDynamicRes (/snapshot/lottery/lib/core/searcher.js)
    at Searcher.checkAllDynamic (/snapshot/lottery/lib/core/searcher.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retryfn (/snapshot/lottery/lib/utils.js)
    at async clear (/snapshot/lottery/lib/clear.js)
    at async main (/snapshot/lottery/main.js)
    at async /snapshot/lottery/main.js

Node.js v18.5.0

`````
