### ISSUE TITLE
清理动态报错

### ISSUE THREAD

**Issue by he778027393** [shanmiteko/LotteryAutoScript#394]
### 描述Bug

清理动态报错

### 重现Bug

清理动态

### 预期行为

1

### 截图

![image](https://github.com/shanmiteko/LotteryAutoScript/assets/51256185/bd7ec118-d3d2-4c21-86b4-036b96fa972a)

### 运行日志

[帐号1 清理动态] [开始读取第369页]
[2024-05-26T20:43:54.524+08] [Info] [帐号1 检查所有动态] [准备读取1页动态]
[2024-05-26T20:43:54.524+08] [Info] [帐号1 检查所有动态] [正在读取其中第1页动态]
[2024-05-26T20:43:54.732+08] [Warn] [帐号1 处理动态数据] [
未找到任何动态信息
]
/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:360
    log.info('处理动态数据', `动态数据读取完毕(${cards.length})(${next.has_more})`);
                                         ^

TypeError: Cannot read properties of null (reading 'length')
    at modifyDynamicRes (/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:360:42)
    at Searcher.checkAllDynamic (/ql/data/scripts/LotteryAutoScript/lib/core/searcher.js:405:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retryfn (/ql/data/scripts/LotteryAutoScript/lib/utils.js:77:19)
    at async clear (/ql/data/scripts/LotteryAutoScript/lib/clear.js:73:59)
    at async main (/ql/data/scripts/LotteryAutoScript/main.js:88:25)
    at async main (/ql/data/scripts/LotteryAutoScript/main.js:41:29)
    at async /ql/data/scripts/LotteryAutoScript/main.js:182:21

Node.js v18.12.1

### 操作系统

青龙

### 脚本版本

2.9.0

**Comment by shanmiteko** [comment]
#392
